# Generated by Django 2.2.8 on 2020-01-27 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('stringLocation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=1)),
                ('difficaullty', models.IntegerField(default=0)),
                ('quality', models.IntegerField(default=0)),
                ('grade_rate', models.IntegerField(default=0)),
                ('overall_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('notebook', models.BooleanField(default=False)),
                ('attendance', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/universities')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('total_score', models.IntegerField(default=0)),
                ('food_rate', models.IntegerField(default=0)),
                ('security_rate', models.IntegerField(default=0)),
                ('location_rate', models.IntegerField(default=0)),
                ('facility_rate', models.IntegerField(default=0)),
                ('internet_rate', models.IntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.University')),
            ],
        ),
    ]
