# Generated by Django 2.2.8 on 2020-01-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20200127_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='overall_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
