# Generated by Django 2.2.8 on 2020-01-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_university_overall_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
