# Generated by Django 2.2.8 on 2020-01-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='overall_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
