# Generated by Django 2.2.8 on 2020-01-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='university',
        ),
    ]
